// Generated by LiveScript 1.3.1
(function(){
  var list_children_names_recursive, expand_depends_on_module, add_children_for_parents, add_parents_for_children, convert_parents_to_children, convert_children_to_parents, preprocessing_options, rename_edge_type, reverse_edge_direction, out$ = typeof exports != 'undefined' && exports || this;
  list_children_names_recursive = function(data, name){
    var output, output_set, i$, ref$, len$, child, j$, ref1$, len1$, rec_child;
    output = [];
    output_set = {};
    output.push(name);
    output_set[name] = true;
    if (data[name] != null && data[name].children != null) {
      for (i$ = 0, len$ = (ref$ = data[name].children).length; i$ < len$; ++i$) {
        child = ref$[i$];
        if (output_set[child] == null) {
          for (j$ = 0, len1$ = (ref1$ = list_children_names_recursive(data, child)).length; j$ < len1$; ++j$) {
            rec_child = ref1$[j$];
            if (output_set[child] == null) {
              output.push(rec_child);
              output_set[rec_child] = true;
            }
          }
        }
      }
    }
    return output;
  };
  out$.expand_depends_on_module = expand_depends_on_module = function(data){
    var network, res$, x, y, topic_name, topic_info, depends_on_module, i$, len$, dependent_module, j$, ref$, len1$, child;
    res$ = {};
    for (x in data) {
      y = data[x];
      res$[x] = import$({}, y);
    }
    network = res$;
    for (topic_name in network) {
      topic_info = network[topic_name];
      depends_on_module = topic_info.depends_on_module;
      if (depends_on_module != null) {
        for (i$ = 0, len$ = depends_on_module.length; i$ < len$; ++i$) {
          dependent_module = depends_on_module[i$];
          if (topic_info.depends == null) {
            topic_info.depends = [];
          }
          for (j$ = 0, len1$ = (ref$ = list_children_names_recursive(data, dependent_module)).length; j$ < len1$; ++j$) {
            child = ref$[j$];
            if (data[child].is_module_only !== true) {
              topic_info.depends.push(child);
            }
          }
        }
      }
    }
    return network;
  };
  out$.add_children_for_parents = add_children_for_parents = function(data){
    var network, res$, x, y, topic_name, topic_info, parents, i$, len$, parent;
    res$ = {};
    for (x in data) {
      y = data[x];
      res$[x] = import$({}, y);
    }
    network = res$;
    for (topic_name in network) {
      topic_info = network[topic_name];
      parents = topic_info.parents;
      if (parents != null) {
        for (i$ = 0, len$ = parents.length; i$ < len$; ++i$) {
          parent = parents[i$];
          if (network[parent] == null) {
            network[parent] = {};
          }
          if (network[parent].children == null) {
            network[parent].children = [];
          }
          network[parent].children.push(topic_name);
        }
      }
    }
    return network;
  };
  out$.add_parents_for_children = add_parents_for_children = function(data){
    var network, res$, x, y, topic_name, topic_info, children, i$, len$, child;
    res$ = {};
    for (x in data) {
      y = data[x];
      res$[x] = import$({}, y);
    }
    network = res$;
    for (topic_name in network) {
      topic_info = network[topic_name];
      children = topic_info.children;
      if (children != null) {
        for (i$ = 0, len$ = children.length; i$ < len$; ++i$) {
          child = children[i$];
          if (network[child] == null) {
            network[child] = {};
          }
          if (network[child].parents == null) {
            network[child].parents = [];
          }
          network[child].parents.push(topic_name);
        }
      }
    }
    return network;
  };
  out$.convert_parents_to_children = convert_parents_to_children = function(data){
    data = reverse_edge_direction('parents', data);
    data = rename_edge_type('parents', 'children', data);
    return data;
  };
  out$.convert_children_to_parents = convert_children_to_parents = function(data){
    data = reverse_edge_direction('children', data);
    data = rename_edge_type('children', 'parents', data);
    return data;
  };
  out$.preprocessing_options = preprocessing_options = {
    convert_parents_to_children: convert_parents_to_children,
    convert_children_to_parents: convert_children_to_parents,
    add_children_for_parents: add_children_for_parents,
    add_parents_for_children: add_parents_for_children,
    expand_depends_on_module: expand_depends_on_module
  };
  out$.rename_edge_type = rename_edge_type = function(orig_name, new_name, data){
    var output, topic_name, topic_info;
    output = {};
    for (topic_name in data) {
      topic_info = data[topic_name];
      topic_info = import$({}, topic_info);
      if (topic_info[orig_name] != null) {
        if (topic_info[new_name] == null) {
          topic_info[new_name] = [];
        }
        topic_info[new_name] = topic_info[new_name].concat(topic_info[orig_name]);
        delete topic_info[orig_name];
      }
      output[topic_name] = topic_info;
    }
    return output;
  };
  out$.reverse_edge_direction = reverse_edge_direction = function(edge_type, data){
    var output, topic_name, topic_info, i$, ref$, len$, child;
    output = {};
    for (topic_name in data) {
      topic_info = data[topic_name];
      topic_info = import$({}, topic_info);
      topic_info[edge_type] = [];
      output[topic_name] = topic_info;
    }
    for (topic_name in data) {
      topic_info = data[topic_name];
      if (topic_info[edge_type] != null) {
        for (i$ = 0, len$ = (ref$ = topic_info[edge_type]).length; i$ < len$; ++i$) {
          child = ref$[i$];
          if (output[child] == null) {
            output[child] = {};
            output[child][edge_type] = [];
          }
          output[child][edge_type].push(topic_name);
        }
      }
    }
    return output;
  };
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
