// Generated by LiveScript 1.3.1
(function(){
  var root;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  $(document).ready(function(){
    var params, topic, output, graph_file, ref$;
    params = getUrlParameters();
    topic = params.topic;
    if (topic == null) {
      $('#curriculum').text('need to provide topic');
      return;
    }
    output = [];
    graph_file = (ref$ = params.graph_file) != null ? ref$ : 'graph.yaml';
    return $.get(graph_file, function(yamltxt){
      var data, i$, ref$, len$, x, item, results$ = [];
      root.rawdata = data = create_terminal_nodes(jsyaml.safeLoad(yamltxt));
      for (i$ = 0, len$ = (ref$ = list_all_related_node_names_recursive(topic)).length; i$ < len$; ++i$) {
        x = ref$[i$];
        output.push(x);
      }
      for (i$ = 0, len$ = (ref$ = output).length; i$ < len$; ++i$) {
        item = ref$[i$];
        results$.push($('#curriculum').append($('<div>').text(item)));
      }
      return results$;
    });
  });
}).call(this);
