// Generated by LiveScript 1.3.1
(function(){
  var express, serveStatic, bing_count, async, app, ref$;
  express = require('express');
  serveStatic = require('serve-static');
  bing_count = require('bing_count');
  async = require('async');
  app = express();
  app.use(serveStatic('.'));
  app.set('port', (ref$ = process.env.PORT) != null ? ref$ : 5000);
  app.listen(app.get('port'), '0.0.0.0');
  app.get('/bingcounts', function(req, res){
    var words, output, tasks, i$, len$;
    words = req.query.words;
    output = {};
    tasks = [];
    if (words == null) {
      res.json([]);
    }
    words = JSON.parse(words);
    for (i$ = 0, len$ = words.length; i$ < len$; ++i$) {
      (fn$.call(this, words[i$]));
    }
    return async.series(tasks, function(){
      return res.json(output);
    });
    function fn$(word){
      tasks.push(function(callback){
        return bing_count(word, function(count){
          output[word] = count;
          return callback(null, null);
        });
      });
    }
  });
}).call(this);
