// Generated by LiveScript 1.3.1
(function(){
  var fs, readEachLine, jsYaml, output;
  fs = require('fs');
  readEachLine = require('read-each-line');
  jsYaml = require('js-yaml');
  output = {};
  readEachLine('graph.csv', function(line){
    var ref$, source, target, value;
    line = line.trim();
    if (line === 'source,target,value') {
      return;
    }
    ref$ = line.split(','), source = ref$[0], target = ref$[1], value = ref$[2];
    value = parseFloat(value);
    if (output[source] != null) {
      return output[source].children.push({
        name: target,
        value: value
      });
    } else {
      return output[source] = {
        children: [{
          name: target,
          value: value
        }]
      };
    }
  });
  fs.writeFileSync('graph.yaml', jsYaml.safeDump(output));
}).call(this);
