// Generated by LiveScript 1.3.1
(function(){
  $(document).ready(function(){
    return $.get('graph.yaml', function(yamltxt){
      var data, links, topic_name, topic_info, i$, ref$, len$, ref1$, name, value;
      data = jsyaml.safeLoad(yamltxt);
      links = [];
      for (topic_name in data) {
        topic_info = data[topic_name];
        for (i$ = 0, len$ = (ref$ = topic_info.children).length; i$ < len$; ++i$) {
          ref1$ = ref$[i$], name = ref1$.name, value = ref1$.value;
          links.push({
            source: topic_name,
            target: name,
            value: value
          });
        }
      }
      return renderLinks(links);
    });
  });
}).call(this);
