// Generated by LiveScript 1.3.1
(function(){
  var ref$, exec, which, existsSync, i$, len$, command;
  ref$ = require('shelljs'), exec = ref$.exec, which = ref$.which;
  existsSync = require('fs').existsSync;
  for (i$ = 0, len$ = (ref$ = ['mongosrv', 'lsc', 'node-dev']).length; i$ < len$; ++i$) {
    command = ref$[i$];
    if (!which(command)) {
      console.log("missing " + command + " command");
      process.exit();
    }
  }
  exec('mongosrv', {
    async: true
  });
  exec('lsc -cw .', {
    async: true
  });
  exec('node-dev app.ls', {
    async: true
  });
}).call(this);
