// Generated by LiveScript 1.3.1
(function(){
  var fs, jsYaml, jsonfile;
  fs = require('fs');
  jsYaml = require('js-yaml');
  jsonfile = require('jsonfile');
  jsonfile.writeFileSync('graph.json', jsYaml.safeLoad(fs.readFileSync('graph.yaml', 'utf-8')));
}).call(this);
