// Generated by LiveScript 1.3.1
(function(){
  var yamlfile, blacklist, main;
  yamlfile = require('yamlfile');
  blacklist = ['graph_metadata'];
  main = function(){
    var infile, outfile, network, topic_name, topic_info, parents, i$, len$, parent;
    infile = process.argv[2];
    outfile = process.argv[3];
    if (infile == null) {
      console.log('need infile');
      return;
    }
    if (outfile == null) {
      console.log('need outfile');
      return;
    }
    network = yamlfile.read(process.argv[2]);
    for (topic_name in network) {
      topic_info = network[topic_name];
      parents = topic_info.parents;
      if (parents != null) {
        for (i$ = 0, len$ = parents.length; i$ < len$; ++i$) {
          parent = parents[i$];
          if (network[parent] == null) {
            network[parent] = {};
          }
          if (network[parent].children == null) {
            network[parent].children = [];
          }
          network[parent].children.push(topic_name);
        }
      }
    }
    for (topic_name in network) {
      topic_info = network[topic_name];
      if (topic_info.parents != null) {
        delete topic_info.parents;
      }
    }
    return yamlfile.write(outfile, network);
  };
  main();
}).call(this);
